spring:
  application:
    name: product-service

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:postgresql://localhost:5432/edureka_ecommerce_db
    username: postgres
    password: 997267
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Automatically creates routes based on Eureka Service IDs
          lower-case-service-id: true